name: Dependency Updates

on:
  schedule:
    - cron: "0 0 * * 1" # Run every Monday at midnight
  workflow_dispatch:

jobs:
  update-dependencies:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Update dependencies
        run: cargo update

      - name: Run tests
        run: cargo test --all-features

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): update dependencies"
          title: "chore(deps): update dependencies"
          body: |
            Automated dependency update.

            This PR updates all dependencies to their latest compatible versions.

            Please review the changes and ensure all tests pass before merging.
          branch: deps/update-dependencies
          delete-branch: true
